# Generated by Django 5.2.1 on 2025-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок блога', max_length=60, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите содержимое блога', verbose_name='Содержимое')),
                ('preview', models.ImageField(help_text='Загрузите изображение блога', upload_to='blog/preview_images', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, help_text='Отметьте для публикации', verbose_name='Опубликовать')),
                ('views_count', models.IntegerField(default=0, help_text='Количество просмотров', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-created_at'],
            },
        ),
    ]
