# Generated by Django 5.2.1 on 2025-06-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите изображение блога', null=True, upload_to='blog_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров', verbose_name='Просмотры'),
        ),
    ]
